### ISSUE TITLE
Create venv workflow and pytest install

### ISSUE THREAD

**Issue by rawrgulmuffins** [bike-barn/red-green-refactor#1]

**Comment by reillysiemens** [comment]
This can be partially addressed by #6. `pytest` won't _need_ to be installed in a virtualenv, but if we want folks to run the application from the command line like
```
~/ $ calc
calc> 3 + 4
7
calc>
```
then it'll be easiest to have them `pip install -e .` in a virtualenv. Otherwise, if we're OK with them just running `./calc/__main__.py` or something then we don't have to worry about a virtualenv at all.

**Comment by rawrgulmuffins** [comment]
This was closed by #17
